const FIGHTERS = [
  {
    id: "jonathan-erasmus",
    name: 'Jonathan "The Wolf" Erasmus',
    short_name: "Jonathan Erasmus",
    status: "Competitor",
    category: "competitor",
    image: "jonathan.jpeg",
    image_position: "center 18%",
    image_scale: 1.08,
    weight_class: "Featherweight",
    mma_record: "3-5-0",
    instagram_url: "https://www.instagram.com/erasmus9563?igsh=MTVnNXpraXp1M2M1cA==",
    achievement: "Bronze Medallist — 2025 SA MMA Nationals",
    bio: 'Jonathan "The Wolf" Erasmus is a fierce featherweight contender stepping into the cage with a 3-5-0 record. He proved his high-level skills on the big stage by battling his way to a strong third-place finish to secure bronze at the 2025 Nationals.'
  },
  {
    id: "damien-erasmus",
    name: 'Damien "The Italian Stallion" Erasmus',
    short_name: "Damien Erasmus",
    status: "Competitor",
    category: "competitor",
    image: "damien-final.jpeg",
    image_position: "center 18%",
    image_scale: 1.03,
    weight_class: "Featherweight",
    mma_record: "2-7-0",
    instagram_url: "https://www.instagram.com/damienerasmus17?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
    achievement: "Silver Medallist — 2025 SA MMA Nationals",
    bio: 'Damien "The Italian Stallion" Erasmus is the number-one ranked featherweight with a 2-7-0 record, highlighted by a first-round KO that helped secure a silver medal at the 2025 Nationals. He also showcased serious grit by battling through five rounds in a championship title fight.'
  },
  {
    id: "austin-armstrong",
    name: "Austin Armstrong",
    short_name: "Austin Armstrong",
    status: "Competitor",
    category: "competitor",
    image: "austin.jpeg",
    image_position: "center 15%",
    image_scale: 1.03,
    weight_class: "Bantamweight",
    mma_record: "0-2-0",
    instagram_url: "",
    achievement: "Hopefield MMA competitor",
    bio: "Hopefield MMA competitor."
  },
  {
    id: "burger-geldenhuys",
    name: "Burger Geldenhuys",
    short_name: "Burger Geldenhuys",
    status: "Former competitor",
    category: "former",
    image: "burger.jpeg",
    image_position: "center 16%",
    image_scale: 1.08,
    weight_class: "",
    mma_record: "",
    instagram_url: "",
    achievement: "Previous Hopefield MMA competitor",
    bio: "Former Hopefield MMA competitor with competition experience."
  },
  {
    id: "seryn-armstrong",
    name: "Seryn Armstrong",
    short_name: "Seryn Armstrong",
    status: "Former competitor",
    category: "former",
    image: "seryn.jpeg",
    image_position: "center 18%",
    image_scale: 1.03,
    weight_class: "",
    mma_record: "1-0-0",
    instagram_url: "",
    achievement: "Previous Hopefield MMA competitor",
    bio: "Former Hopefield MMA competitor with a 1-0-0 record."
  },
  {
    id: "shamiel-sierbritz",
    name: "Shamiel Sierbritz",
    short_name: "Shamiel Sierbritz",
    status: "Future competitor",
    category: "future",
    image: "samil.jpeg",
    image_position: "center 16%",
    image_scale: 1.03,
    weight_class: "",
    mma_record: "",
    instagram_url: "",
    achievement: "Preparing for future competition",
    bio: "Hopefield MMA athlete preparing for future competition."
  },
  {
    id: "juande-jansen",
    name: "Juande Jansen",
    short_name: "Juande Jansen",
    status: "Future competitor",
    category: "future",
    image: "juande.jpeg",
    image_position: "center 16%",
    image_scale: 1.03,
    weight_class: "",
    mma_record: "",
    instagram_url: "",
    achievement: "Preparing for future competition",
    bio: "Hopefield MMA athlete preparing for future competition."
  }
];

const GALLERY = [
  {src:"first-fight-team.jpeg", alt:"Hopefield MMA team at competition"},
  {src:"damien-action-1.jpeg", alt:"Hopefield MMA competition action"},
  {src:"damien-action-2.jpeg", alt:"Hopefield MMA fight action"},
  {src:"damien-action-3.jpeg", alt:"Hopefield MMA cage action"},
  {src:"burger-2.jpeg", alt:"Hopefield MMA competition photo"},
  {src:"damien-press.jpeg", alt:"Hopefield MMA media event"},

  {src:"gallery-faceoff-01.jpg", alt:"Hopefield MMA pre-fight faceoff"},
  {src:"gallery-coach-medal.jpg", alt:"Hopefield MMA coach and fighter after competition"},
  {src:"gallery-faceoff-02.webp", alt:"Hopefield MMA official faceoff"},
  {src:"gallery-cage-venue.jpg", alt:"MMA cage and event venue before competition"},
  {src:"gallery-travel-medals.jpg", alt:"Hopefield MMA athletes travelling with competition medals"},
  {src:"gallery-faceoff-03.jpg", alt:"Hopefield MMA weigh-in faceoff"},
  {src:"gallery-faceoff-04.jpg", alt:"Hopefield MMA competition faceoff"},
  {src:"gallery-faceoff-05.jpg", alt:"Women competitors at an MMA faceoff"},
  {src:"gallery-faceoff-06.jpg", alt:"MMA competitors at a pre-fight faceoff"},
  {src:"gallery-walkout.jpeg", alt:"Hopefield MMA fighter walkout at an event"}
];