const FIGHTERS = [
  {
    id: "jonathan-erasmus",
    name: 'Jonathan "The Wolf" Erasmus',
    short_name: "Jonathan Erasmus",
    status: "Competitor",
    category: "competitor",
    image: "assets/profile-jonathan.jpeg",
    image_position: "center 18%",
    image_scale: 1.08,
    weight_class: "Featherweight",
    mma_record: "3-5-0",
    instagram_url: "https://www.instagram.com/erasmus9563?igsh=MTVnNXpraXp1M2M1cA==",
    achievement: "Bronze Medallist — 2025 SA MMA Nationals",
    bio: 'Jonathan "The Wolf" Erasmus is a fierce featherweight contender stepping into the cage with a 3-5-0 record. He proved his high-level skills on the big stage by battling his way to a strong third-place finish to secure bronze at the 2025 Nationals.'
  },
  {
    id: "damien-erasmus",
    name: 'Damien "The Italian Stallion" Erasmus',
    short_name: "Damien Erasmus",
    status: "Competitor",
    category: "competitor",
    image: "assets/profile-damien.jpeg",
    image_position: "center 18%",
    image_scale: 1.03,
    weight_class: "Featherweight",
    mma_record: "2-7-0",
    instagram_url: "https://www.instagram.com/damienerasmus17?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
    achievement: "Silver Medallist — 2025 SA MMA Nationals",
    bio: 'Damien "The Italian Stallion" Erasmus is the number-one ranked featherweight with a 2-7-0 record, highlighted by a first-round KO that helped secure a silver medal at the 2025 Nationals. He also showcased serious grit by battling through five rounds in a championship title fight.'
  },
  {
    id: "austin-armstrong",
    name: "Austin Armstrong",
    short_name: "Austin Armstrong",
    status: "Competitor",
    category: "competitor",
    image: "assets/profile-austin.jpeg",
    image_position: "center 15%",
    image_scale: 1.03,
    weight_class: "Bantamweight",
    mma_record: "0-2-0",
    instagram_url: "",
    achievement: "Hopefield MMA competitor",
    bio: "Hopefield MMA competitor."
  },
  {
    id: "burger-geldenhuys",
    name: "Burger Geldenhuys",
    short_name: "Burger Geldenhuys",
    status: "Former competitor",
    category: "former",
    image: "assets/profile-burger.jpeg",
    image_position: "center 16%",
    image_scale: 1.08,
    weight_class: "",
    mma_record: "",
    instagram_url: "",
    achievement: "Previous Hopefield MMA competitor",
    bio: "Former Hopefield MMA competitor with competition experience."
  },
  {
    id: "seryn-armstrong",
    name: "Seryn Armstrong",
    short_name: "Seryn Armstrong",
    status: "Former competitor",
    category: "former",
    image: "assets/profile-seryn.jpeg",
    image_position: "center 18%",
    image_scale: 1.03,
    weight_class: "",
    mma_record: "1-0-0",
    instagram_url: "",
    achievement: "Previous Hopefield MMA competitor",
    bio: "Former Hopefield MMA competitor with a 1-0-0 record."
  },
  {
    id: "shamiel-sierbritz",
    name: "Shamiel Sierbritz",
    short_name: "Shamiel Sierbritz",
    status: "Future competitor",
    category: "future",
    image: "assets/profile-shamiel.jpeg",
    image_position: "center 16%",
    image_scale: 1.03,
    weight_class: "",
    mma_record: "",
    instagram_url: "",
    achievement: "Preparing for future competition",
    bio: "Hopefield MMA athlete preparing for future competition."
  },
  {
    id: "juande-jansen",
    name: "Juande Jansen",
    short_name: "Juande Jansen",
    status: "Future competitor",
    category: "future",
    image: "assets/profile-juande.jpeg",
    image_position: "center 16%",
    image_scale: 1.03,
    weight_class: "",
    mma_record: "",
    instagram_url: "",
    achievement: "Preparing for future competition",
    bio: "Hopefield MMA athlete preparing for future competition."
  }
];

const GALLERY = [
  {src:"assets/team-event.jpeg", alt:"Hopefield MMA team at competition"},
  {src:"assets/action-1.jpeg", alt:"Hopefield MMA competition action"},
  {src:"assets/action-2.jpeg", alt:"Hopefield MMA fight action"},
  {src:"assets/action-3.jpeg", alt:"Hopefield MMA cage action"},
  {src:"assets/team-podium.jpeg", alt:"Hopefield MMA team at an event"},
  {src:"assets/grappling.jpeg", alt:"MMA grappling action"},
  {src:"assets/press.jpeg", alt:"Combat sports media event"},
  {src:"assets/team-prep.jpeg", alt:"Hopefield MMA team preparation"},
  {src:"assets/fight-action.jpeg", alt:"Hopefield MMA cage action"}
];
